# Exercise

In [5]:
import numpy as np


In [76]:
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
arr1 = np.ones(10)
print(arr1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


##### give two solution

In [71]:
arr1 = np.ones(10)*6
arr1


array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [75]:
arr1 = np.zeros(10)+6
arr1

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [77]:
arr2 = np.arange(1,60,5)
print(arr2)

[ 1  6 11 16 21 26 31 36 41 46 51 56]


In [78]:
arr3 = np.arange(10,51,1)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [79]:
arr3 = np.arange(2,25,2)
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

##### give two solution

In [81]:
arr2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Generate Random Number between 1 to 2

In [61]:
np.random.rand(2,3)

array([[0.30049983, 0.74578291, 0.16095942],
       [0.61332969, 0.73215442, 0.87795872]])

#### Generate random number of 25 using standard normal distrubution

In [62]:
np.random.randn(25)

array([-0.47440708, -0.6993665 ,  1.09080079,  1.67835666,  1.36702632,
       -0.23960306,  1.96217016,  0.22628886,  0.29098168, -1.85624518,
        0.51919427, -0.84606666,  1.26443632,  0.18725268,  0.54537287,
        0.08323255, -0.62278142,  0.03237758, -1.03619821,  0.50348892,
        0.09849751,  0.6625356 , -0.96342808,  0.31094645, -0.18060589])

In [65]:
np.arange(0,1.01,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [85]:
arr = np.linspace(0.01,1,100).reshape(10,10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

##### 20 linearly spaced points between 0 to 1

In [86]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.random.rand()

In [69]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##### sum of elements of matrix

In [70]:
mat.sum()

325

##### grab this matrix from mat 

In [87]:
mat[2:,1: ]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [89]:
mat[3,4]

20

In [95]:
mat1 = mat[0:3,1]
print(mat1)

[ 2  7 12]


In [96]:
mat1 = mat[0:3,1:2]
print(mat1)

[[ 2]
 [ 7]
 [12]]


##### get sum of the all column in mat

In [97]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])